name: PWA Build Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check PWA Files
        run: |
          echo "Checking PWA files..."
          ls -la
          if [ -f "manifest.json" ]; then
            echo "✓ manifest.json exists"
            cat manifest.json
          else
            echo "✗ manifest.json missing"
            exit 1
          fi
          
          if [ -f "sw.js" ]; then
            echo "✓ sw.js exists"
            cat sw.js
          else
            echo "✗ sw.js missing"
            exit 1
          fi
          
          echo "All PWA files check passed!" 