name: PWA Build Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check PWA Files
        run: |
          if [ -f "manifest.json" ] && [ -f "sw.js" ]; then
            echo "PWA files exist"
          else
            echo "Missing PWA files"
            exit 1 